#bowtie2-build reference.fa pathogen_name
#PhageM13_amplicon.fa 파일을 따로 생성할 것:
#>PhageM13_flank5
#ACCGATACAA TTAAAGGCTC CTTTTGGAGC CTTTTTTTTG GAGATTTTCA
#ACGTGAAAAA ATTATTATTC GCAATTCCTT TAGTGGTACC TTTCTATTCT
#CACTCT
#>PhageM13_flank3
#GGTGGAGG
#TTCGGCCGAA ACTGTTGAAA GTTGTTTAGC AAAATCCCAT ACAGAAAATC
#ATTACTAACG TCTGGAAAGA CGACAA                           

bowtie2-build PhageM13_amplicon.fa PhageM13
